ENV['MAILER_EMAIL'] = 'railsfinalproject@gmail.com'
ENV['MAILER_PASSWORD'] = 'railsproject'

# ENV['RECAPTCHA_PUBLIC_KEY'] = '6Lc6Pl0UAAAAAPVRMtpW69ib8lePeqinK4vNqlV9'
# ENV['RECAPTCHA_PRIVATE_KEY'] = '6Lc6Pl0UAAAAAErNOLMqMj3-mb8K3zPgiK3PrfYX'
